spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: "!smj435821"

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: "A5b4c3d2e1."

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/saessac?serverTimezone=UTC&characterEncoding=UTF-8
#    username: "root"
#    password: "A5b4c3d2e1."

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.194.141:3306/saessac?serverTimezone=UTC&characterEncoding=UTF-8
    username: "saessacki"
    password: "1234"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        use-new-id-generator-mappings: false

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type:
    descriptor:
      sql:
        BasicBinder: TRACE

server:
  port: 80