spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Deleted datasource information for security
    # To use this application, insert database url before "/saessac"
    # Insert username, password to access database
    ## "saessac" schema dumps are backed up on https://github.com/Saessak2/Saessak-Database
    url: jdbc:mysql:///saessac?useSSL=false&useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ""
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        use-new-id-generator-mappings: false

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type:
    descriptor:
      sql:
        BasicBinder: TRACE

server:
  port: 8080